name: protondrive-linux
version: '1.0.0'
summary: ProtonDrive Linux GUI Client
description: |
  Unofficial desktop client for ProtonDrive on Linux.
  Features sync, browse, and mount functionality via rclone backend.

base: core22
confinement: strict
grade: stable

apps:
  protondrive-linux:
    command: bin/protondrive-gui
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  rclone:
    plugin: dump
    source: https://github.com/rclone/rclone/releases/download/v1.70.3/rclone-v1.70.3-linux-amd64.zip
    stage:
      - rclone
    prime:
      - rclone

  protondrive-linux:
    plugin: python
    source: https://github.com/donniedice/protondrive-linux.git
    source-tag: v1.0.0
    python-packages:
      - .
    stage-packages:
      - python3-tk