import { app, BrowserWindow, ipcMain, session } from 'electron';
import { sdkBridge } from '../services/sdk-bridge';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string; // Corrected constant for preload

// Declare mainWindow globally to prevent it from being garbage collected.
let mainWindow: BrowserWindow | null;

// Handle creating/removing shortcuts on Windows when installing/uninstallation.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Global error handling for the main process
process.on('uncaughtException', (error) => {
  console.error('Unhandled Rejection in main process:', error);
  app.quit();
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection in main process:', reason, promise);
  app.quit();
});


const createWindow = (): void => {
  try {
    // Create the browser window.
    mainWindow = new BrowserWindow({
      height: 600,
      width: 800,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, // Use the corrected preload constant
        contextIsolation: true, // Keep this true for security
        nodeIntegration: false, // Keep this false for security
        sandbox: true,
        webSecurity: true,
        allowRunningInsecureContent: false,
        experimentalFeatures: false,
      },
      show: false, // Don't show until 'ready-to-show' event
    });

    // Show window only when the page has finished rendering
    mainWindow.once('ready-to-show', () => {
      if (mainWindow) {
        mainWindow.show();
        console.log('Window is ready and shown.');
      }
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)
      .then(() => {
        console.log('Window loaded successfully.');
      })
      .catch((error) => {
        console.error('Window failed to load URL:', error);
      });

    // Open the DevTools.
    mainWindow.webContents.openDevTools();

    // Event handlers for renderer process issues
    mainWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription, validatedURL, isMainFrame) => {
      console.error(`Window did-fail-load: URL=${validatedURL}, Code=${errorCode}, Description=${errorDescription}, MainFrame=${isMainFrame}`);
    });

    mainWindow.webContents.on('unresponsive', () => {
      console.error('Window became unresponsive.');
    });

    mainWindow.webContents.on('render-process-gone', (event, details) => {
      console.error(`Window render process gone: reason=${details.reason}, exitCode=${details.exitCode}`);
    });

    // Dereference the window object when the window is closed
    mainWindow.on('closed', () => {
      mainWindow = null;
      console.log('Main window closed, dereferencing.');
    });

  } catch (error) {
    console.error('Error during createWindow:', error);
    app.quit(); // Ensure app quits if window creation itself fails
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();

  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': ["default-src 'self'"]
      }
    })
  });

  // Start the Java SDK bridge
  sdkBridge.start();
});

// Handle messages from renderer to Java SDK
ipcMain.handle('sdk-message', async (event, message: { method: string; args: any[] }) => {
  console.log('Main: Received IPC message from renderer:', message); // New log
  try {
    const response = await sdkBridge.sendMessage(message);
    console.log('Main: Sending response back to renderer:', response); // New log
    return response;
  } catch (error: any) {
    console.error(`Main: Error in sdk-message handler for method ${message.method}:`, error);
    return { error: error.message };
  }
});


// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// Stop the Java SDK process before the app quits
app.on('before-quit', () => {
  sdkBridge.stop();
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.